name: "GitHub Readme Sync Prep"
description: "Generate all the Markdown Frontmatter needed by Readme.io so your docs look cleaner in GitHub."
inputs:
  docsdirectory:
    description: "Name of directory we will look at"
    required: true
    default: "./docs"
  ignorelist:
    description: "Comma separated list of directories under the docs directory we should ignore"
    required: true
    default: "images"
  readmeapikey:
    description: "API Key for readme.io"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
